"""The tax-registry source's own tables, and its foreign key on the run ledger.

Revision ID: 0017
Revises: 0016
Created: 2026-08-14

Hand-written, not autogenerated (H10). Ruled 2026-08-14 (D85): the 財政部 全國營業(稅籍)登記
資料集 is the sixth reference source, and the first that publishes a **category the business
chose for itself** — the 行業代號 it registered under, beside the name the tax office holds.

**Only the rows the reference list already knows are stored**, ruled the same day. The served
file is 1,711,012 rows nationwide; the latest place publication offers about 19.2k distinct
統編 and about 14.5k of them match. Storing the rest would multiply this table by two hundred
to hold rows about businesses no circle in this product can eat at. The cost is that a 統編
appearing in a *later* place publication is not retro-filled — the next tax publication picks
it up, and the join is per-publication anyway.

Shape, and the measured facts that forced it:

  * **統編 is unique in this file** — 1,711,012 rows, 0 duplicates, every one of them eight
    numeric digits (measured 2026-08-14). So the primary key is `(publication_id,
    business_no)` and not D81's four-column tuple: that roster had genuine 統編 reuse, this
    file does not.
  * **The four 行業 pairs are positional.** No row carries a later code while its primary one
    is empty, so the first pair is the business's own primary 行業 and compacting the empty
    tail would promote a secondary one into a slot that means "primary".
  * **`address` is the registered address, not the storefront.** 13.7% of the matched rows are
    registered outside 臺北市 altogether — 3,130 of them: an accountant's office, a head office, a
    home. The address a diner walks to stays `reference_place.address`, and nothing may join on
    this one. *(This line read 6.2% when the revision landed, from a 2026-08-14 reading; the
    cross-source measurement three days later put it at 13.66% and the text was corrected
    2026-09-11. The schema this revision creates is untouched.)*

The publication pattern is 0016's, plus the second version signal item 11 has and D77/D78/D81
lack: `file_stamp` is the date the CSV states about itself in its own row 2, kept beside the
content hash and never used as the key (D35). `ingest_run` gains its seventh foreign key (D24),
and the two counting CHECKs are rebuilt to count seven.
"""

from alembic import op
import sqlalchemy as sa

revision = "0017"
down_revision = "0016"
branch_labels = None
depends_on = None

ONE_PUBLICATION = (
    "num_nonnulls(forecast_publication_id, observation_publication_id, "
    "place_publication_id, brand_publication_id, storefront_publication_id, "
    "business_status_publication_id{tax}) <= 1"
)
STORED_HAS_PUBLICATION = (
    "(outcome = 'stored') = (num_nonnulls(forecast_publication_id, "
    "observation_publication_id, place_publication_id, brand_publication_id, "
    "storefront_publication_id, business_status_publication_id{tax}) = 1)"
)


def upgrade() -> None:
    op.create_table(
        "business_tax_publication",
        sa.Column("id", sa.BigInteger, primary_key=True),
        # `fia-business-tax` — 全國營業(稅籍)登記資料集, 財政部財政資訊中心.
        sa.Column("source", sa.Text, nullable=False),
        sa.Column("content_sha256", sa.CHAR(64), nullable=False),
        # The file's own version signal: row 2 of the CSV, `14-AUG-26`, as a date. Nullable
        # because an unreadable stamp row is a missing label rather than a failed run — the
        # hash still identifies the publication, and the verdict says the label was lost.
        sa.Column("file_stamp", sa.Date, nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_bytes", sa.Integer, nullable=False),
        sa.Column("entry_name", sa.Text, nullable=False),
        sa.Column("entry_bytes", sa.BigInteger, nullable=False),
        sa.Column("scope", sa.Text, nullable=False),
        sa.Column("tax_rows", sa.Integer, nullable=True),
        # The sibling publications' key. One source in play, so this is `content_sha256`
        # unique in practice; the pair is kept because `claim`'s `on conflict` names it and a
        # second publisher of the same shape would need it.
        sa.UniqueConstraint(
            "source", "content_sha256", name="uq_business_tax_publication_content"
        ),
        sa.CheckConstraint("payload_bytes > 0", name="ck_business_tax_publication_nonempty"),
    )
    op.create_index(
        "ix_business_tax_publication_detected", "business_tax_publication", ["detected_at"]
    )

    op.create_table(
        "business_tax_row",
        sa.Column("publication_id", sa.BigInteger, nullable=False),
        sa.Column("business_no", sa.Text, nullable=False),
        # The name the tax office holds. A third spelling of the same business, beside FDA's
        # registered name and D78's shop sign — kept for the read side to rank, never folded
        # here (D80 owns which name wins).
        sa.Column("tax_name", sa.Text, nullable=False),
        # **The REGISTERED address, not the storefront.** 13.7% of these are outside 臺北市.
        # Nothing joins on it and nothing may start: it is audit context for a matched 統編.
        sa.Column("address", sa.Text, nullable=False),
        # The primary 行業 pair, then the three optional ones, positional and never compacted.
        sa.Column("industry_code", sa.Text, nullable=True),
        sa.Column("industry_name", sa.Text, nullable=True),
        sa.Column("industry_code_1", sa.Text, nullable=True),
        sa.Column("industry_name_1", sa.Text, nullable=True),
        sa.Column("industry_code_2", sa.Text, nullable=True),
        sa.Column("industry_name_2", sa.Text, nullable=True),
        sa.Column("industry_code_3", sa.Text, nullable=True),
        sa.Column("industry_name_3", sa.Text, nullable=True),
        sa.ForeignKeyConstraint(
            ["publication_id"], ["business_tax_publication.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("publication_id", "business_no"),
        sa.CheckConstraint("business_no <> ''", name="ck_business_tax_row_no"),
    )
    # The read path's whole question: the 行業 of one number, within one publication. The
    # primary key already answers it, so the only index worth adding is the one that finds
    # every shop of a code — the shape D63's classifier would compare itself against.
    op.create_index(
        "ix_business_tax_row_industry", "business_tax_row", ["publication_id", "industry_code"]
    )

    op.add_column(
        "ingest_run", sa.Column("business_tax_publication_id", sa.BigInteger, nullable=True)
    )
    op.create_foreign_key(
        "fk_ingest_run_business_tax_publication",
        "ingest_run",
        "business_tax_publication",
        ["business_tax_publication_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("ck_ingest_run_one_publication", "ingest_run", type_="check")
    op.drop_constraint("ck_ingest_run_stored_has_publication", "ingest_run", type_="check")
    op.create_check_constraint(
        "ck_ingest_run_one_publication",
        "ingest_run",
        ONE_PUBLICATION.format(tax=", business_tax_publication_id"),
    )
    op.create_check_constraint(
        "ck_ingest_run_stored_has_publication",
        "ingest_run",
        STORED_HAS_PUBLICATION.format(tax=", business_tax_publication_id"),
    )


def downgrade() -> None:
    op.drop_constraint("ck_ingest_run_one_publication", "ingest_run", type_="check")
    op.drop_constraint("ck_ingest_run_stored_has_publication", "ingest_run", type_="check")
    op.create_check_constraint(
        "ck_ingest_run_one_publication", "ingest_run", ONE_PUBLICATION.format(tax="")
    )
    op.create_check_constraint(
        "ck_ingest_run_stored_has_publication", "ingest_run", STORED_HAS_PUBLICATION.format(tax="")
    )
    op.drop_constraint("fk_ingest_run_business_tax_publication", "ingest_run", type_="foreignkey")
    op.drop_column("ingest_run", "business_tax_publication_id")
    op.drop_table("business_tax_row")
    op.drop_table("business_tax_publication")
