"""A12 / D71 — the reading a round's rain factors were measured against.

Revision ID: 0030
Revises: 0029
Created: 2026-08-27

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-27, shape (b) of three put to him.

**Why a table and not a column.** D71 is relative now: a place's factor is `1 − gap/120` where
`gap` is its township's 降雨機率 minus **the lowest in the round's pool**. That minimum is a
property of the round, not of any one place — every contribution in the round is measured against
the same reading — so a column on `weight_contribution` would store one fact N times.

**Why anything at all: D24 has a hole without it.** A contribution pins the reading it was computed
from, and `ck_contribution_exactly_one_source` allows exactly one source pin per row. The place
standing on the minimum produces **no contribution** (D43: no difference, no record), so before this
table the baseline reading was pinned by nothing and the lineage tool could not name it — which is
what RR-8 asks for. It did survive, transitively: A12 makes the whole pool read from one
publication, and that publication cannot be deleted while any contribution pins a reading in it. But
*survives* and *can be named* are different questions, and D24 is about the second.

**Rejected: a second forecast pin on the contribution** — five more columns, a new FK, and a change
to `ck_contribution_exactly_one_source`, which is the constraint that made the preference
contribution possible and is documented as the pattern the next source will follow. It would also
store the same five values on every row of a round.
**Rejected: nothing at all**, relying on the transitive survival above. Real protection, and not an
answer to *which reading was the baseline*.

**One row per round, so `round_id` is the primary key.** A round has one pool, one target hour and
one publication, therefore one baseline.

**A round may have none, and that is a legal state rather than a gap.** A pool with no `reference`
place, a pool whose townships the chosen publication does not carry, an hour with no reading — each
means nothing was compared, so there is no baseline to record. The row's absence says *no comparison
happened*; a row with every township equal says *a comparison happened and found no difference*.
Those are different facts and D112 is the reason they must not collapse into one.

**The probability is NOT stored, and that is D28.** The number is in the pinned `forecast_reading`
row; a copy here would be a second value to drift, and the composite FK guarantees the original is
still there to read.

**`ON DELETE RESTRICT` on the reading, `CASCADE` on the round.** D24's pattern both ways: a reading
some round measured against cannot be deleted, and a round that is deleted takes its own baseline
with it.
"""

from alembic import op
import sqlalchemy as sa

revision = "0030"
down_revision = "0029"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "round_forecast_baseline",
        sa.Column("round_id", sa.BigInteger, primary_key=True),
        sa.Column("publication_id", sa.BigInteger, nullable=False),
        sa.Column("township_code", sa.Text, nullable=False),
        sa.Column("element", sa.Text, nullable=False),
        sa.Column("measure", sa.Text, nullable=False),
        sa.Column("slot_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["round_id"], ["round.id"], ondelete="CASCADE"),
        # The whole primary key of `forecast_reading`, in its own column order — the same shape
        # `weight_contribution`'s forecast pin uses, so the two are read the same way.
        sa.ForeignKeyConstraint(
            ["publication_id", "township_code", "element", "measure", "slot_start"],
            ["forecast_reading.publication_id", "forecast_reading.township_code",
             "forecast_reading.element", "forecast_reading.measure",
             "forecast_reading.slot_start"],
            name="fk_round_baseline_reading",
            ondelete="RESTRICT",
        ),
    )


def downgrade() -> None:
    op.drop_table("round_forecast_baseline")
