"""A14 / D114 — a contribution may be about the circle's last signed trip.

Revision ID: 0031
Revises: 0030
Created: 2026-08-27

Hand-written, not autogenerated (H10). Owner-ruled via orchestrator 2026-08-27, on the shape
proposed from the constraint rather than around it.

**This is the widening revision 0022 predicted by name.** Its note on
`ck_contribution_exactly_one_source` says the change was recorded there rather than only in a commit
message because *"the next source (a coupon, D30's partner) will meet the same constraint and should
find the pattern already stated"*. The next source turned out to be a trip rather than a coupon; the
pattern is the one that was written down, and this migration is that paragraph carried out.

**Why a column and not something cheaper.** D24 requires a contribution to record **which row** it
was computed from, so a re-read reproduces the number and a row some round used cannot be erased.
A trip's identity is its own `id`, and nothing already on `weight_contribution` can carry it — the
three existing pins name a forecast reading, an observation reading and a preference version. There
is no way to express a fourth source without a fourth key.

**`ON DELETE RESTRICT`, like every other pin here.** A trip some round measured against cannot be
deleted. D114's factor is *because the circle went there*, so the row that says they went is exactly
the row the arithmetic leans on.

**Nullable, and the CHECK is what makes that safe.** Every pin column here is nullable and
`num_nonnulls(...) = 1` is what forbids a row with none and a row with two. The count goes from
three to four; the rule does not change.

**Nothing is backfilled and nothing needs to be.** No contribution has ever been about a trip, so
`trip_id` is NULL on every existing row and the widened CHECK accepts all of them unchanged — the
count of non-nulls is still exactly one on each.

**No index.** The column is written by the engine and read by a pin, never queried on. An index
here would be a guess about a query nobody has.
"""

from alembic import op
import sqlalchemy as sa

revision = "0031"
down_revision = "0030"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("weight_contribution", sa.Column("trip_id", sa.BigInteger, nullable=True))
    op.create_foreign_key(
        "fk_contribution_trip", "weight_contribution", "trip",
        ["trip_id"], ["id"], ondelete="RESTRICT",
    )
    op.drop_constraint("ck_contribution_exactly_one_source", "weight_contribution", type_="check")
    op.create_check_constraint(
        "ck_contribution_exactly_one_source", "weight_contribution",
        "num_nonnulls(forecast_publication_id, observation_publication_id, preference_id, "
        "trip_id) = 1",
    )


def downgrade() -> None:
    op.drop_constraint("ck_contribution_exactly_one_source", "weight_contribution", type_="check")
    op.create_check_constraint(
        "ck_contribution_exactly_one_source", "weight_contribution",
        "num_nonnulls(forecast_publication_id, observation_publication_id, preference_id) = 1",
    )
    op.drop_constraint("fk_contribution_trip", "weight_contribution", type_="foreignkey")
    op.drop_column("weight_contribution", "trip_id")
