"""A15 / D115 — the four service roles get exactly the reach their boundary allows.

Revision ID: 0032
Revises: 0031
Created: 2026-08-27

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-27 (D115, and the `upto_erasure`
amendment the same day).

**The map is in `upto.roles` and this file only issues it.** The migration and the coverage test
import the same dict, so the grants and the check cannot disagree — one boundary, one spelling.
Read that module before changing anything here.

**The roles are created by `airflow/init.sh`, not here, and this fails loudly if one is missing.**
A migration cannot hold a password, and a role without one cannot log in; `init.sh` has the three
from `.env` and creates them in the same delete-then-add shape as the Connections (D33). So the
order on a fresh clone is `docker compose up` (init.sh creates the roles) → `alembic upgrade head`
(this grants). Getting that backwards used to produce `role "upto_api" does not exist` from deep
inside a GRANT; it now produces a sentence naming `init.sh`.

**Every grant is preceded by a REVOKE of everything**, so re-running this after the map narrows
actually narrows it. A migration that only ever adds privileges cannot express a boundary moving
inward, and a boundary that can only widen is not one.

**Sequences are granted with the tables that own them.** `INSERT` on a table whose primary key is a
`bigserial` fails with *permission denied for sequence* unless the role also holds `USAGE` on it —
a refusal that reads as a bug in the insert rather than as a missing grant, which is why it is done
here rather than discovered later.

**No `ALTER DEFAULT PRIVILEGES`, deliberately.** It would make every future table readable by a role
automatically, which is exactly the silence D115's cost paragraph refuses: a new table must carry
its grants or the coverage test goes red. Convenience here would buy off the mechanism that makes
the boundary checkable.
"""

from alembic import op
import sqlalchemy as sa

revision = "0032"
down_revision = "0031"
branch_labels = None
depends_on = None


def _roles():
    import sys

    sys.path.insert(0, "/srv/src")
    from upto import roles as role_map  # noqa: PLC0415

    return role_map


def upgrade() -> None:
    role_map = _roles()
    connection = op.get_bind()

    missing = [
        name
        for name in role_map.SERVICE_ROLES
        if connection.execute(
            sa.text("select 1 from pg_roles where rolname = :n"), {"n": name}
        ).scalar_one_or_none()
        is None
    ]
    if missing:
        raise RuntimeError(
            "these roles do not exist: {}. They are created by `airflow/init.sh` from the "
            "passwords in app/.env, because a migration cannot hold one. Bring the stack up "
            "(`docker compose up -d --wait`) so init.sh runs, then re-run this migration.".format(
                ", ".join(missing)
            )
        )

    grants = role_map.grants()
    for role, tables in grants.items():
        # Connect and see the schema at all. Without it every grant below is unreachable.
        op.execute(sa.text('grant usage on schema public to "{}"'.format(role)))
        # **Narrowing has to be expressible.** Revoke first, then grant what the map says today.
        op.execute(
            sa.text('revoke all on all tables in schema public from "{}"'.format(role))
        )
        op.execute(
            sa.text('revoke all on all sequences in schema public from "{}"'.format(role))
        )
        for table, privileges in sorted(tables.items()):
            op.execute(
                sa.text(
                    'grant {} on "{}" to "{}"'.format(", ".join(privileges), table, role)
                )
            )
            if "insert" in privileges:
                # The sequences this table owns — its own serial columns and no others.
                for sequence in connection.execute(
                    sa.text(
                        "select s.relname from pg_class s "
                        " join pg_depend d on d.objid = s.oid and d.deptype = 'a' "
                        " join pg_class t on t.oid = d.refobjid "
                        "where s.relkind = 'S' and t.relname = :t"
                    ),
                    {"t": table},
                ).scalars():
                    op.execute(
                        sa.text(
                            'grant usage, select on sequence "{}" to "{}"'.format(sequence, role)
                        )
                    )


def downgrade() -> None:
    role_map = _roles()
    for role in role_map.SERVICE_ROLES:
        op.execute(sa.text('revoke all on all tables in schema public from "{}"'.format(role)))
        op.execute(sa.text('revoke all on all sequences in schema public from "{}"'.format(role)))
        op.execute(sa.text('revoke usage on schema public from "{}"'.format(role)))
