"""A18 / D42 as amended — an observation publication records what it stored, not just what it fetched.

Revision ID: 0033
Revises: 0032
Created: 2026-08-28

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-28
(「匯入時只留臺北市，之前太異想天開，一次就做全台」).

**What changed above this column.** The CWA observation ingest fetched 876 stations and stored all
of them — 7,884 rows an hour, of which 臺北市 is 19 stations and 171 rows (2.2%), measured on the
live database the day this landed. The product never read the other 97.8%: D26 resolves a township
to a Taipei station and D57 reads the latest publication per hour. The filter now runs at **store**
time, after the content hash, so D42's change detection and D102's `column_signature` still see the
whole file — what narrows is what is kept, never what is identified.

**Why the publication has to say so.** Without this column the ledger shows 7,884 rows an hour and
then 171, and there is no way to tell a narrowed scope from a broken fetch. That is D112's rule
applied to a number: an absence needs a shape, or it reads as a presence — here, as a source that
half fell over.

**`NULL` means the whole publication was stored, and that is true of every existing row** — so
nothing is backfilled and nothing needs to be. The rows heal in the only direction that matters:
every publication written from now on says what it kept.

**Only this table, deliberately.** The other six publication tables store everything their source
publishes, and a `stored_scope` column on them would assert a filter that does not exist — D112
inverted, a shape given to an absence that has none. The forecast table is the clearest case: its
scope is `F-D0047-061`, *the Taipei township forecast*, so the dataset id is the filter and we
apply none. Measured the same day: its latest publication holds 6,720 rows over exactly twelve
township codes, all prefixed `63000`.

**What reads it today: a person.** A9's `check_publication` does **not** cover the weather ingest —
`_publication_check.SOURCES` names five sources and neither CWA dataset is among them — so the
20%-collapse line cannot fire on the first filtered run, which the ticket asked for and the absence
already gave. The day weather joins A9, `_read_previous` should filter on this column, and the first
filtered run then reads *n/a* rather than *collapse*: A9's own designed behaviour, no special case.
"""

from alembic import op
import sqlalchemy as sa

revision = "0033"
down_revision = "0032"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "observation_publication",
        sa.Column("stored_scope", sa.Text(), nullable=True),
    )
    op.execute(
        sa.text(
            "comment on column observation_publication.stored_scope is "
            "'A18: the county whose rows this publication kept. NULL = the whole publication was "
            "stored, which is every row written before 2026-08-28. The hash and column_signature "
            "always cover the whole file.'"
        )
    )


def downgrade() -> None:
    op.drop_column("observation_publication", "stored_scope")
