"""D42's retention amendment — `upto_erasure` may delete weather readings past the window.

Revision ID: 0034
Revises: 0033
Created: 2026-08-28

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-28 (「依照建議」): ninety days, both
weather tables, unpinned rows only, one daily job.

**Why this role and not `upto_ingest`.** The pipeline role already holds DELETE on both tables, and
it is still the wrong one: the job's `UNPINNED` filter must read `weight_contribution`, and D115
gives `upto_ingest` **nothing** there — §3.0 and D14 say the pipeline never sees a person. Widening
it would undo the line A15 exists to draw. `upto_erasure` already holds that SELECT for D24's
pinned-preference filter and its purpose is unchanged: delete on a schedule, skip what a round
pinned. Only the table list moves.

**The grants are read from `upto.roles` and not typed here**, the same as revision 0032 — the
migration that issues them and the test that checks their coverage import one dict, so the boundary
cannot be spelled two ways.
"""

from alembic import op
import sqlalchemy as sa

revision = "0034"
down_revision = "0033"
branch_labels = None
depends_on = None

ADDED = {
    "observation_reading": ("select", "delete"),
    "forecast_reading": ("select", "delete"),
    "round_forecast_baseline": ("select",),
    "observation_publication": ("select",),
    "forecast_publication": ("select",),
}


def _erasure_role() -> str:
    import importlib.util
    import os

    path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        "src", "upto", "roles.py",
    )
    spec = importlib.util.spec_from_file_location("_upto_roles", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.ERASURE


def upgrade() -> None:
    role = _erasure_role()
    for table, privileges in ADDED.items():
        op.execute(
            sa.text('grant {} on "{}" to "{}"'.format(", ".join(privileges), table, role))
        )


def downgrade() -> None:
    role = _erasure_role()
    for table in ADDED:
        op.execute(sa.text('revoke all on "{}" from "{}"'.format(table, role)))
