"""A19 / D103 as amended — what a brand's products are made of, as the platform published it.

Revision ID: 0035
Revises: 0034
Created: 2026-08-29

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-28 (「蝦就是甲殼類」 and 「算」).

**No new source.** These rows come out of the file D77 already downloads — data.taipei 00004058,
resource `29869b6f…`, the same fetch, the same hash, the same `ingest_run`. The platform publishes
one row per *ingredient of one product*, and until now this pipeline kept the (company, brand) pair
and discarded the rest. D103's ingredient block was inert *for want of store-published data* that
had been arriving daily and being thrown away.

**The allergen group is NOT a column here, and that is the design rather than an omission.** What is
stored is what the publisher published; the group is decided at read time by
`upto.seed.ingredient_terms`, which is authored, dated and in git. Storing the group would freeze
one day's version of that table into the rows, and the table's whole value is that a term added
tomorrow re-answers every row already held — D28's read-time rule, and D92's for the same reason.

**Keyed on the publication, so a republication is a new set and old rows stay readable.** A
contribution that leaned on a past answer needs the publication it read to still exist, which is
what every other reference table here does.

**`material_name_raw` beside `material_name` (H24).** The normalised form is what joins; the raw
form is what the publisher wrote, and a name argued about later is argued about against theirs.
"""

from alembic import op
import sqlalchemy as sa

revision = "0035"
down_revision = "0034"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "product_material",
        sa.Column("publication_id", sa.BigInteger(),
                  sa.ForeignKey("brand_publication.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("company_name", sa.Text(), nullable=False),
        sa.Column("brand_name", sa.Text(), nullable=False),
        sa.Column("product_name", sa.Text(), nullable=False),
        sa.Column("material_name", sa.Text(), nullable=False),
        sa.Column("material_name_raw", sa.Text(), nullable=False),
        # The four names identify the row within its publication; the platform repeats a material
        # across a product's variants and the parse already dedupes on exactly this tuple.
        sa.PrimaryKeyConstraint("publication_id", "company_name", "brand_name", "product_name",
                                "material_name", name="pk_product_material"),
    )
    # The read is always "this company's materials, in the latest publication" — D77's join key.
    op.create_index(
        "ix_product_material_company",
        "product_material",
        ["publication_id", "company_name"],
    )
    op.execute(
        sa.text(
            "comment on table product_material is "
            "'A19: one raw material of one product, as 臺北市食材登錄平台 published it. The allergen "
            "group is derived at read time from upto.seed.ingredient_terms and is deliberately not "
            "a column — see the migration.'"
        )
    )


    # **H10's rule extends to grants (D115): a new table ships with its constraint AND its grants,
    # or it is unreachable by every service and `test_role_grants` says so.** The privileges are
    # read from `upto.roles` rather than typed here — one dict, so the boundary cannot be spelled
    # two ways — exactly as revision 0032 does.
    role_map = _roles()
    for role, tables in role_map.grants().items():
        privileges = tables.get("product_material")
        if not privileges:
            continue
        op.execute(
            sa.text('grant {} on "product_material" to "{}"'.format(
                ", ".join(privileges), role))
        )


def _roles():
    """Imported as a package, not loaded as a file — and revision 0034 got away with the other way.

    `roles.grants()` does `from .lineage.queries import READABLE_TABLES` (H20's boundary, read from
    the list it enforces), and a relative import needs a parent package. Loading `roles.py` through
    `importlib.util.spec_from_file_location` gives it none, so `grants()` raises *attempted relative
    import with no known parent package* — while 0034, which reads only a constant from the same
    module, never reaches that line and works. Same loader, two outcomes, and the difference is
    which attribute you touch. This is 0032's shape and the one to copy.
    """
    import sys

    sys.path.insert(0, "/srv/src")
    from upto import roles as role_map  # noqa: PLC0415

    return role_map


def downgrade() -> None:
    op.drop_index("ix_product_material_company", table_name="product_material")
    op.drop_table("product_material")
