"""A19 / D24 — a contribution may be about the brand publication it read an ingredient from.

Revision ID: 0036
Revises: 0035
Created: 2026-08-29

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-29 (「接受」).

**The fifth source, and revision 0031 named the shape.** That migration widened
`ck_contribution_exactly_one_source` from three to four for A14's trip and wrote down that the next
source would meet the same constraint and should find the pattern already stated. This is that
paragraph carried out a second time; the rule does not change, only the count.

**Why the PUBLICATION and not a `product_material` row — the ticket asked for the row and it does
not survive contact.** An ingredient veto reads **every product of a brand**: the member avoids 蛋,
and the question is whether *anything* this brand publishes names it. There is no single row the
answer came from — there are 87 of them for 全家, and a pin on one of them would be a true fact
about an arbitrary member of the set. What D24 actually requires is that **a re-read reproduces the
number**, and the input that reproduces it is the publication.

*Rejected on the record:* pinning a `product_material` row (an arbitrary member of a set, and the
answer would survive that row's deletion unchanged, so the pin would protect nothing that matters).

**What the authored table's absence from the pin means, stated rather than left implicit.** The
group is decided by `upto.seed.ingredient_terms`, which is code in git and not a row. A re-read
after a term is added CAN produce a different answer, and that is deliberate — it is the same
read-time shape D92's naming ladder has, and the reason the table is worth keeping. D24 pins rows
so a row cannot be erased underneath a number; it has never pinned code, and this does not start.

**`ON DELETE RESTRICT`, like every other pin here.** A brand publication some round leaned on cannot
be deleted. Nothing deletes brand publications today; the constraint is what keeps that true if
something ever does.

**Nothing is backfilled and nothing needs to be.** No contribution has ever been about an
ingredient, so every existing row has four NULLs among five and the widened CHECK holds for all of
them unchanged.

**Grants: none to issue, and that is checked rather than assumed.** The grants in `upto.roles` are
per **table**, not per column, and `weight_contribution` already carries every role's line —
`upto_erasure` reads the whole row for D24's pinned-preference filter and gains nothing new here.
H59's rule (a creating migration issues its own grants) applies to a created *table*; this creates a
column on a table that already has its grants, so there is nothing to issue and `test_role_grants`
stays the check that says so.
"""

from alembic import op
import sqlalchemy as sa

revision = "0036"
down_revision = "0035"
branch_labels = None
depends_on = None

SOURCES = (
    "forecast_publication_id",
    "observation_publication_id",
    "preference_id",
    "trip_id",
    "brand_publication_id",
)


def upgrade() -> None:
    op.add_column(
        "weight_contribution",
        sa.Column("brand_publication_id", sa.BigInteger(), nullable=True),
    )
    op.create_foreign_key(
        "fk_contribution_brand_publication",
        "weight_contribution",
        "brand_publication",
        ["brand_publication_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # Dropped and recreated rather than altered: a CHECK has no ALTER, and naming the new one the
    # same keeps every reference to it — in code, in tests and in D24 — pointing at one constraint.
    op.drop_constraint("ck_contribution_exactly_one_source", "weight_contribution",
                       type_="check")
    op.create_check_constraint(
        "ck_contribution_exactly_one_source",
        "weight_contribution",
        "num_nonnulls({}) = 1".format(", ".join(SOURCES)),
    )


def downgrade() -> None:
    op.drop_constraint("ck_contribution_exactly_one_source", "weight_contribution",
                       type_="check")
    op.create_check_constraint(
        "ck_contribution_exactly_one_source",
        "weight_contribution",
        "num_nonnulls({}) = 1".format(", ".join(s for s in SOURCES
                                                if s != "brand_publication_id")),
    )
    op.drop_constraint("fk_contribution_brand_publication", "weight_contribution",
                       type_="foreignkey")
    op.drop_column("weight_contribution", "brand_publication_id")
