"""D13 as amended 2026-08-30 — a reason may be its member's on the panel without being on the reveal.

Revision ID: 0037
Revises: 0036
Created: 2026-08-30

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-30 (「縮小」).

**Why a migration at all, when the brief said none was needed.** `ck_contribution_visibility` is a
closed list — `table` · `represented_member` · `none` — so a fourth value is refused by the database,
not merely undeclared. `reason_visibility` looked like free text and is not, and the failure would
have arrived at the first roll where a member avoids a category, as a CHECK violation on the write
rather than as anything about the ruling. Checked before building rather than after.

**What changes and what deliberately does not.** The **category** discount takes
`represented_member_panel`; the **ingredient** veto keeps `represented_member`, and `my_reasons`
keeps selecting exactly that. **The new value attaches to the thing being narrowed, not to the thing
being kept** — so the reveal's predicate never learns a second value, nothing silently joins it, and
a fifth contributor has to choose between two named audiences instead of inheriting the reveal.

**The reason for the narrowing, in one line, because the value's name cannot carry it:** a category
sentence restates the chip the member set themselves and removed nothing; an ingredient veto is a
fact about a place they cannot eat in and appears nowhere else.

**Nothing is backfilled and the old rows are not wrong.** Every existing `represented_member` row was
written by the category contributor under the old rule, and it meant *this member's own* — which is
still true. They will read on the reveal until they age out, which is the honest consequence of not
rewriting history to match a rule made after it.
"""

from alembic import op
import sqlalchemy as sa

revision = "0037"
down_revision = "0036"
branch_labels = None
depends_on = None

VALUES = ("table", "represented_member", "represented_member_panel", "none")


def upgrade() -> None:
    op.drop_constraint("ck_contribution_visibility", "weight_contribution", type_="check")
    op.create_check_constraint(
        "ck_contribution_visibility",
        "weight_contribution",
        "reason_visibility in ({})".format(", ".join("'{}'".format(v) for v in VALUES)),
    )


def downgrade() -> None:
    # **A row already carrying the new value would refuse the narrower CHECK, and that is correct.**
    # A downgrade past this point has to decide what those rows mean; it is not this migration's to
    # guess, and failing loudly is better than rewriting somebody's visibility on the way down.
    op.drop_constraint("ck_contribution_visibility", "weight_contribution", type_="check")
    op.create_check_constraint(
        "ck_contribution_visibility",
        "weight_contribution",
        "reason_visibility in ('table', 'represented_member', 'none')",
    )
