"""A22 — `upto_backup` may read everything and change nothing.

Revision ID: 0038
Revises: 0037
Created: 2026-08-30

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-30 against running the nightly
`pg_dump` as the database owner.

**Why a fifth role rather than the owner, which the ticket first specified.** Under LocalExecutor
the backup task runs inside `airflow-scheduler` — forced, not chosen: `pg_dump` exists in the
airflow images and not in the api/tests image (H1), and Airflow cannot start a one-shot compose
service without the docker socket, which is a worse privilege than the one being avoided. That
container is long-lived and shared by eleven DAGs, and D115's line is that only a job which
*exits* holds the owner. So the job gets a role that can read the whole database and write none
of it: `DROP DATABASE` leaves the blast radius of a bug in that process.

**Measured before it was ruled, not argued:** a throwaway role holding only `pg_read_all_data`
produced a dump with the same 32 `TABLE DATA` entries and 19,687,927 bytes against the owner's
19,687,878 — a 49-byte header difference and nothing else.

**`pg_read_all_data` and not a table list, and that is the load-bearing choice.** A backup that
silently omits a table added last week is the worst failure this ticket has: it looks green every
night and is discovered during a restore, which is the one moment nobody has time. A predefined
role covers every table that exists and every table that will, so the backup cannot drift out of
step with the schema the way a hand-maintained list would. The cost, stated: this role can read
every `preference` row, so it is *less* powerful than the owner and not harmless — a leaked backup
credential is still a leaked copy of the database, which is why it is its own password, rotated
the same way as the other four.

**Not in `SERVICE_ROLES`, and H61 is why.** `test_role_grants.ungranted_tables` proves "a table
added without grants goes red" by asking whether any service role can SELECT it. This one can
SELECT everything.

`pg_read_all_data` is PostgreSQL 14+; the server here is 17.11.

**⚠️ This grant is cluster-scoped and outlives the database it was issued in — read H62.** Every
grant before this revision was `on <table>`, which dies with the database; a role membership does
not. `test_role_grants` builds a temporary database, runs this step and drops it, and the
membership stays in the cluster. Benign here, because it is the grant the live database wants
anyway; recorded because the next migration to touch a role may not be.
"""

from alembic import op
import sqlalchemy as sa

revision = "0038"
down_revision = "0037"
branch_labels = None
depends_on = None


def _backup_role() -> str:
    """The role name from `upto.roles`, so it is spelled once.

    **H59's rule, and this step is safe under it**: what is read from the shared map here is a
    *name*, not a table list. A name cannot drift out of step with the schema of the moment the
    way `product_material` did — there is no table for this step to reach for that might not
    exist yet.
    """
    import importlib.util
    import os

    path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        "src", "upto", "roles.py",
    )
    spec = importlib.util.spec_from_file_location("_upto_roles", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.BACKUP


def upgrade() -> None:
    role = _backup_role()
    # **Guarded, and not out of caution.** `roles.ensure()` creates the login roles and runs in the
    # same one-shot `migrate` service immediately before Alembic — but a database restored from a
    # dump taken *before* this revision, then migrated forward by hand, reaches here with the role
    # absent. That is the A22 drill's own path, so the failure mode is one this ticket creates.
    op.execute(
        sa.text(
            "do $$ begin "
            "  if exists (select 1 from pg_roles where rolname = '{role}') then "
            "    grant pg_read_all_data to \"{role}\"; "
            "  else "
            "    raise notice 'role {role} absent — grant skipped; run upto.roles first'; "
            "  end if; "
            "end $$;".format(role=role)
        )
    )


def downgrade() -> None:
    role = _backup_role()
    op.execute(
        sa.text(
            "do $$ begin "
            "  if exists (select 1 from pg_roles where rolname = '{role}') then "
            "    revoke pg_read_all_data from \"{role}\"; "
            "  end if; "
            "end $$;".format(role=role)
        )
    )
