"""D38's eleventh value reaches the preference CHECK — a member may avoid 便利商店.

Revision ID: 0039
Revises: 0038
Created: 2026-08-30

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-30
(「我認為可以開一類就是便利商店」), and the surface half of the same ruling that gave the
classifier its eleventh value in `upto/classify/categories.py`.

**Why this constraint and no other.** `place.category` has **no value CHECK** — the only thing in
the schema that names D38's list is `ck_preference_category_value`, which governs what a member may
**avoid**. So the classifier could store `便利商店` from the moment its own list grew; what could
not happen until now is a member ticking the chip. One constraint, one migration.

**The list is typed out here and not imported, and that is H59's rule.** `preferences.CATEGORIES`
is application code that will keep moving; a migration reading it would apply *today's* list to a
step in the past, which is exactly how revision 0032 came to grant over a table that did not exist
yet. The values are frozen in this file, dated, and the coverage between the two is a **test**'s
job (`test_preference_integration` asserts the CHECK accepts every value the module lists).

**Recreate rather than `ALTER … ADD`**: a CHECK cannot be widened in place, and dropping before
adding under one transaction is how every other value list here has moved (0037's four-value
visibility, one revision back).
"""

from alembic import op
import sqlalchemy as sa

revision = "0039"
down_revision = "0038"
branch_labels = None
depends_on = None

# D38 as amended 2026-08-30. Frozen here on purpose — see the docstring.
ELEVEN = ("麵食", "飯食", "小吃", "火鍋", "燒烤", "日式", "西式", "早餐", "咖啡飲料",
          "便利商店", "其他")
TEN = tuple(value for value in ELEVEN if value != "便利商店")

CONSTRAINT = "ck_preference_category_value"


def _rule(values) -> str:
    return "kind <> 'avoid_category' or value in ({})".format(
        ", ".join("'{}'".format(value) for value in values)
    )


def upgrade() -> None:
    op.execute(sa.text('alter table preference drop constraint "{}"'.format(CONSTRAINT)))
    op.execute(sa.text('alter table preference add constraint "{}" check ({})'.format(
        CONSTRAINT, _rule(ELEVEN))))


def downgrade() -> None:
    # **Loud rather than lossy.** Narrowing back while a member holds the new value would fail on
    # the constraint anyway; failing here says which rows and why, instead of leaving a reader to
    # read a Postgres error about a constraint they have not met.
    held = op.get_bind().execute(sa.text(
        "select count(*) from preference where kind = 'avoid_category' and value = '便利商店'"
    )).scalar()
    if held:
        raise RuntimeError(
            "{} preference row(s) avoid 便利商店. Narrowing this CHECK would refuse them, and "
            "deleting a member's stated preference to undo a schema change is not this "
            "migration's decision to make.".format(held)
        )
    op.execute(sa.text('alter table preference drop constraint "{}"'.format(CONSTRAINT)))
    op.execute(sa.text('alter table preference add constraint "{}" check ({})'.format(
        CONSTRAINT, _rule(TEN))))
