"""D38's twelfth and thirteenth values reach the preference CHECK — 台菜 and 素食.

Revision ID: 0040
Revises: 0039
Created: 2026-08-30

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-30 (「加兩類」), the surface half of the
same ruling that took `upto/classify/categories.py` to thirteen.

**Why these two and not the others that were proposed.** `其他` held 15,146 of 27,982 decided rows,
and the two largest actionable things inside it were **台菜** and **素食**. `甜點` was held: 489 rows
spread over bakeries, shaved-ice stalls and cake shops are three kinds of shop sharing one word, and
nobody proposes dinner at a bakery. `中式` was rejected and replaced by **台菜** because 麵食, 飯食,
火鍋, 燒烤 and 小吃 are all Chinese food — a 中式 value is a residual on arrival.

**`小館` is not 台菜, owner-ruled, and it is the reason this migration exists rather than a bigger
one.** Measured first: 211 city names carry 小館 against 47 熱炒/快炒 and 24 explicit 台菜/合菜, and
the 小館 rows the model did place went to 小吃, 西式, 火鍋, 日式 and 麵食 — 綵肴客家小館 is Hakka.
台菜 is the explicit words only.

**`place.category` still has no value CHECK**, so this constraint — what a member may **avoid** — is
again the only schema object naming D38's list. The values are frozen here rather than imported
(H59: a migration reading shared code applies today's list to a step in the past).
"""

from alembic import op
import sqlalchemy as sa

revision = "0040"
down_revision = "0039"
branch_labels = None
depends_on = None

# D38 as amended 2026-08-30 (「加兩類」). Frozen here on purpose — see the docstring.
THIRTEEN = ("麵食", "飯食", "小吃", "火鍋", "燒烤", "日式", "西式", "早餐", "咖啡飲料",
            "便利商店", "台菜", "素食", "其他")
ADDED = ("台菜", "素食")
ELEVEN = tuple(value for value in THIRTEEN if value not in ADDED)

CONSTRAINT = "ck_preference_category_value"


def _rule(values) -> str:
    return "kind <> 'avoid_category' or value in ({})".format(
        ", ".join("'{}'".format(value) for value in values)
    )


def upgrade() -> None:
    op.execute(sa.text('alter table preference drop constraint "{}"'.format(CONSTRAINT)))
    op.execute(sa.text('alter table preference add constraint "{}" check ({})'.format(
        CONSTRAINT, _rule(THIRTEEN))))


def downgrade() -> None:
    # Loud rather than lossy, the same as 0039: narrowing while a member holds one of the new
    # values would fail on the constraint anyway, and deleting a stated preference to undo a
    # schema change is not this migration's decision to make.
    held = op.get_bind().execute(sa.text(
        "select count(*) from preference where kind = 'avoid_category' and value in ('台菜', '素食')"
    )).scalar()
    if held:
        raise RuntimeError(
            "{} preference row(s) avoid 台菜 or 素食. Narrowing this CHECK would refuse them."
            .format(held)
        )
    op.execute(sa.text('alter table preference drop constraint "{}"'.format(CONSTRAINT)))
    op.execute(sa.text('alter table preference add constraint "{}" check ({})'.format(
        CONSTRAINT, _rule(ELEVEN))))
