"""Rung 2 — a crib row records the prefix convention it was embedded under.

Revision ID: 0041
Revises: 0040
Created: 2026-08-31

Hand-written, not autogenerated (H10).

**The failure this prevents, and it is one the existing checks CANNOT see.** `example_embedding`'s
unique key was `(embed_model, name)`. Several embedders want an instruction or a `query:` prefix
and lose 1–5% without it, so rung 2 adds one — and the moment it is added, **the same model string
produces different vectors**. Loading a prefixed crib would `upsert` over the bare rows under the
same key, leaving half the store in each convention. `embed.py`'s own docstring says why nothing
would catch it: both vectors are well-formed, both are the right width, and they mean different
things. Neighbours would then be ordered by nothing.

**It also destroys the experiment.** Rung 2 isolates the prefix effect on the incumbent by running
`snowflake-arctic-embed2` **both ways**; without this column the second run overwrites the baseline
it is being compared against.

So the convention joins the identity: `(embed_model, prefix_kind, name)`.

**Backfill: every existing row is `none`, and that is a fact rather than a default.** Every vector
in the table today was embedded by a client that sent raw text — the prefixing did not exist. The
column is `NOT NULL` so a future row cannot omit it, and `embed.prefix_kind()` returns the string
`unknown` for a model nobody has recorded, which is deliberately not `none`: `none` claims the text
was sent bare, `unknown` says nobody knows, and a crib mixing those is what this revision exists to
make impossible.
"""

from alembic import op
import sqlalchemy as sa

revision = "0041"
down_revision = "0040"
branch_labels = None
depends_on = None

OLD = "uq_example_embedding_model_name"
NEW = "uq_example_embedding_model_prefix_name"


def upgrade() -> None:
    op.execute(sa.text(
        "alter table example_embedding add column prefix_kind text not null default 'none'"
    ))
    # The default did the backfill; dropping it makes the next writer state the convention rather
    # than inherit a guess.
    op.execute(sa.text("alter table example_embedding alter column prefix_kind drop default"))
    op.execute(sa.text(
        "alter table example_embedding add constraint ck_example_embedding_prefix_kind "
        "check (prefix_kind in ('none', 'query', 'instruct', 'unknown'))"
    ))
    # **`drop constraint`, not `drop index` — 0019 created it as a CONSTRAINT.** The first
    # version of this migration said `drop index if exists`, which fails with
    # `DependentObjectsStillExistError: … constraint … requires it` and, worse, the `if exists`
    # made it read as a safe no-op. The build-and-drop test caught it; the live database never
    # would have, because this only runs on a fresh migration. Added as a constraint for the same
    # reason: the two must stay the same kind of object.
    op.execute(sa.text('alter table example_embedding drop constraint "{}"'.format(OLD)))
    op.execute(sa.text(
        'alter table example_embedding add constraint "{}" '
        '  unique (embed_model, prefix_kind, name)'.format(NEW)
    ))


def downgrade() -> None:
    # **Loud rather than lossy.** Narrowing the key back would refuse two rows that differ only by
    # convention — which is the state this revision exists to allow — so it says which rows and
    # why instead of letting Postgres report a duplicate nobody expected.
    clash = op.get_bind().execute(sa.text(
        "select count(*) from (select embed_model, name from example_embedding "
        "  group by 1, 2 having count(distinct prefix_kind) > 1) t"
    )).scalar()
    if clash:
        raise RuntimeError(
            "{} (embed_model, name) pair(s) hold more than one prefix convention. Narrowing the "
            "key would refuse them, and choosing which vector to delete is not this migration's "
            "decision — re-load the crib you want and drop the other first.".format(clash)
        )
    op.execute(sa.text('alter table example_embedding drop constraint "{}"'.format(NEW)))
    op.execute(sa.text(
        'alter table example_embedding add constraint "{}" unique (embed_model, name)'.format(OLD)
    ))
    op.execute(sa.text(
        "alter table example_embedding drop constraint ck_example_embedding_prefix_kind"
    ))
    op.execute(sa.text("alter table example_embedding drop column prefix_kind"))
