"""A crib row records WHERE it came from, and only frozen-set rows are held out of retrieval.

Revision ID: 0042
Revises: 0041
Created: 2026-09-03

Hand-written, not autogenerated (H10).

**Why, in one line: D88's leave-one-out was written for a crib whose rows ARE the population
being classified, and the brand rows are not that.** The owner ruled 「縮」 on 2026-09-03 — D88's
2026-09-03 amendment — narrowing the exclusion from «exclude the asked string» to «exclude the
asked string **among rows that came from the frozen set**».

**The measurement that produced the ruling.** `nearest(exclude_name=name)` filters on the name
alone, in the round runner *and* in `classify/run.py`. Of the 4,091 brand-joined places carrying an
asked string (D80's `category_input`), **3,832 — 93.7% — are asked as exactly the brand**, so a
crib row named `麥當勞` was invisible to every one of them. On the frozen set the same rule hid
five of the eight reachable misses. The rule was doing exactly what D88 designed it to do; what
changed is that the store now holds a second kind of row.

**Three columns, and each earns its place.**

1. **`source`** — `'testset'` or `'brand'`. The exclusion keys on it, and so do `stored_sha` and
   `replace_all`: reloading the frozen set must not delete the brand rows, and a brand load must
   not delete the frozen set. 0019 scoped those to `embed_model` for the same reason one embedder's
   load must not cost another its cells; this is that argument one axis further.

2. **`testset_sha256` becomes `source_digest`.** The column always meant «the digest of the set
   this row was built from»; only its name assumed there was one kind of set. A brand row storing
   its provenance in a column called `testset_sha256` would be false on its face, and
   `stored_sha`'s own error message talks about «test-set digests» to a reader who may be holding
   a brand-load fault. The rename is the cheap half of keeping that honest.

3. **`source_ref`** — NULL for frozen-set rows, and for a brand row the D77 row it came from
   (`brand_publication` id and `company_name`). The label's authors stay in `labeled_by`, by full
   model identity rather than a nickname (H68). Together those answer «who said this, and on what
   published basis» without reading prose, which is D113's shape and the reason a brand row may be
   trusted at all.

**The unique key gains `source`, and that is not tidiness — it is measured.** Five names are in
both sets today: `麥味登`, `CAMA`, `Krispy Kreme Doughnuts`, `五桐號`, `味亦美` are frozen-set rows
**and** D77 brands. Under 0041's `(embed_model, prefix_kind, name)` the brand load would collide
with the exam's own rows and upsert over them. Both rows must exist: the frozen-set one is held
out when its name is asked, the brand one is not, and that difference is the whole ruling.

**Backfill: every existing row is `'testset'`, and that is a fact rather than a default.** The
store has only ever been loaded from the frozen set. The column is `NOT NULL` so a future writer
must state the source rather than inherit one.
"""

from alembic import op
import sqlalchemy as sa

revision = "0042"
down_revision = "0041"
branch_labels = None
depends_on = None

OLD = "uq_example_embedding_model_prefix_name"
NEW = "uq_example_embedding_model_prefix_source_name"


def upgrade() -> None:
    op.execute(sa.text(
        "alter table example_embedding add column source text not null default 'testset'"
    ))
    # The default did the backfill; dropping it makes the next writer state the source rather than
    # inherit a guess — 0041's reasoning about `prefix_kind`, unchanged.
    op.execute(sa.text("alter table example_embedding alter column source drop default"))
    op.execute(sa.text(
        "alter table example_embedding add constraint ck_example_embedding_source "
        "check (source in ('testset', 'brand'))"
    ))
    op.execute(sa.text(
        "alter table example_embedding rename column testset_sha256 to source_digest"
    ))
    op.execute(sa.text("alter table example_embedding add column source_ref text"))
    # A frozen-set row has no D77 row behind it and a brand row must name one: the pairing is
    # asserted here rather than left to the loader, because a brand row with no basis is exactly
    # the row D113 refuses.
    op.execute(sa.text(
        "alter table example_embedding add constraint ck_example_embedding_source_ref "
        "check ((source = 'testset' and source_ref is null) "
        "    or (source = 'brand' and source_ref is not null and source_ref <> ''))"
    ))
    # **`drop constraint`, not `drop index`** — 0019 created it as a CONSTRAINT and 0041 was bitten
    # by exactly this; the `if exists` form reads as a safe no-op and is not one.
    op.execute(sa.text('alter table example_embedding drop constraint "{}"'.format(OLD)))
    op.execute(sa.text(
        'alter table example_embedding add constraint "{}" '
        '  unique (embed_model, prefix_kind, source, name)'.format(NEW)
    ))


def downgrade() -> None:
    # **Loud rather than lossy**, 0041's rule. Narrowing the key back would refuse the five names
    # that legitimately exist under both sources, and choosing which to delete is not this
    # migration's decision.
    clash = op.get_bind().execute(sa.text(
        "select count(*) from (select embed_model, prefix_kind, name from example_embedding "
        "  group by 1, 2, 3 having count(distinct source) > 1) t"
    )).scalar()
    if clash:
        raise RuntimeError(
            "{} (embed_model, prefix_kind, name) triple(s) hold rows from more than one source — "
            "the frozen set and D77 share these names by measurement. Narrowing the key would "
            "refuse them; drop the source you do not want first.".format(clash)
        )
    op.execute(sa.text('alter table example_embedding drop constraint "{}"'.format(NEW)))
    op.execute(sa.text(
        'alter table example_embedding add constraint "{}" '
        '  unique (embed_model, prefix_kind, name)'.format(OLD)
    ))
    op.execute(sa.text(
        "alter table example_embedding drop constraint ck_example_embedding_source_ref"
    ))
    op.execute(sa.text("alter table example_embedding drop column source_ref"))
    op.execute(sa.text(
        "alter table example_embedding rename column source_digest to testset_sha256"
    ))
    op.execute(sa.text("alter table example_embedding drop constraint ck_example_embedding_source"))
    op.execute(sa.text("alter table example_embedding drop column source"))
