"""`upto_api` may read `alembic_version`, because the startup guard is the reason it exists.

Revision ID: 0043
Revises: 0042
Created: 2026-09-11

Hand-written, not autogenerated (H10).

**The measurement this revision exists for.** Candidate 15 moved D115's «a failed migration stops
the API» from `depends_on` into the code (`upto/schema_guard.py`). The reviewer's re-read on
2026-09-11 found that the guard **never fires in the product**, and it was reproduced inside
`upto-api-1`:

    connected as upto_api
    REFUSED: InsufficientPrivilegeError permission denied for table alembic_version

The guard reads `alembic_version` through the server's own session, which connects as `upto_api`.
That role held no grant on the table — `roles.OWNER_ONLY` — so every startup took
`check_or_exit`'s «could not be checked — serving anyway» branch and served whatever schema it
found. **The integration test passed the whole time because it ran the guard as the owner**, which
is the shape of a test proving the rule rather than the wiring.

**So the grant is SELECT and nothing else, on one table, for one role.** `upto_api` may read which
revision the database is at; it may not write it, and no other role's reach moves. Alembic itself
writes that row as the owner, from `migrate`, which is the whole point of 「一次」.

**Why the table stops being `OWNER_ONLY` rather than the guard changing connection.** The
alternative was a second URL in the api container — the owner's, or a fourth role — opened at
startup purely to read one string. That is a credential at rest in the one container D115 spent
its argument getting credentials *out* of, to save a grant of SELECT on a table holding a single
version string that every migration file in the public repository already names. The reach this
adds is the ability to learn a number that is published; the reach the alternative adds is the
owner in the serving process.

**What moves with it:** `roles.OWNER_ONLY` loses its only entry and gains an explicit map of what
non-owner roles may do to Alembic's bookkeeping, and `test_role_grants`' «`alembic_version` is the
one named exception» line becomes an assertion that `upto_api` holds SELECT and that no role holds
anything more. D115's entry carries the amendment.

**Where the grant actually lands, which is not always here** (the reviewer's note, 2026-09-11).
`roles.grants()` folds `ALEMBIC_GRANTS` in, and revision **0032** issues whatever that map says
today for every table that exists at its point in the history — `alembic_version` exists before
any migration runs. So on a **fresh** database the grant is issued at 0032 and this revision is a
no-op re-grant; on an **existing** one 0032 has long since run and this revision is the fix. Both
paths end at the same state, which is what matters, and 0032's own comment explains why it reads
the live map. The paragraph below is therefore about the *downgrade* path alone.

**⚠️ One consequence, measured rather than reasoned about — `downgrade` takes the grant with it.**
A database rolled back below this revision is one the guard can no longer read, so instead of
«the database is at 0042 and this code ships against 0044» it says «alembic_version could not be
READ … revision 0043 grants that SELECT». **It still refuses to serve**, which is the part that
matters, and the message names the revision to reach — but the pair of revisions is not available
to it, because the thing it would need in order to name them is the grant that was just revoked.
Pinned in `test_schema_guard_integration` as its own case, so the message a reader actually meets
on a pre-0043 database is the one asserted, not the one assumed.
"""

from alembic import op
import sqlalchemy as sa

revision = "0043"
down_revision = "0042"
branch_labels = None
depends_on = None

TABLE = "alembic_version"


def _api_role() -> str:
    """Read the role's NAME from `roles.py` — the name is stable, the maps in that file are not.

    Same shape as 0034, and H59's rule is why only the name is read: a migration that imported a
    *list* from application code would apply today's list to a step in the past.
    """
    import importlib.util
    import os

    path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        "src", "upto", "roles.py",
    )
    spec = importlib.util.spec_from_file_location("_upto_roles", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.API


def upgrade() -> None:
    op.execute(sa.text('grant select on "{}" to "{}"'.format(TABLE, _api_role())))


def downgrade() -> None:
    op.execute(sa.text('revoke all on "{}" from "{}"'.format(TABLE, _api_role())))
