"""A24 — one shared join ticket per circle, stored as a hash.

Revision ID: 0044
Revises: 0043
Created: 2026-09-13

Hand-written, not autogenerated (H10).

**The ruling (self-serve sitting ②, owner 「1」, 2026-09-13).** Friends join by one shared link the
creator pastes into the group; whoever taps it grows their own seat and types their own nickname.
D110's `SEAT_CAP` bounds the scale. *Rejected: one link per friend — administration, not asking
people to dinner.*

**Why a row rather than a signed value, which is the cheaper shape.** A signed token (an HMAC over
the circle id, verified with a server key) needs no table and no write on the join path. It cannot
be **revoked**: doing so needs either a server-side list of dead tickets — this table, arrived at by
the back door and worse, because it would grow for ever — or rotating the signing key, **which
kills every circle's ticket at once in order to revoke one.** Revocation was asked for, so the
ticket is a row. (A24's research paragraph.)

**`token_sha256`, never the token.** The same property D74 gives a device secret: the plaintext is
printed once at issue and lives only in the group chat, so **a database read cannot produce a
working ticket**. The unique index is on the hash, which is also what makes the lookup on the join
path a single index probe.

**`expires_at` is nullable and nothing sets it yet.** Null means «no expiry», which is the
recommendation in A24 — an expiring ticket fails silently in the *common* path (a friend tapping on
Thursday a link posted on Monday, refused, while the person who could fix it is not in the
conversation), revocation covers the case expiry is reached for, and the nightly idle sweep is
already the outer bound because a ticket cannot outlive its circle. **The column ships now on the
orchestrator's word because it is the same shape under either ruling and a nullable column costs
nothing;** whether anything ever writes it is the owner's, and until he rules, the join path treats
a non-null value as binding. A check that no row has one would be wrong — it would have to be
dropped to honour the other ruling.

**One live ticket per circle, and it is a partial unique index rather than a column.** `revoked_at
is null` is the liveness test, so the constraint is «at most one unrevoked ticket per circle» and
revoked rows accumulate as the record of who replaced what. Re-issue is one transaction: revoke,
then insert. A `current_ticket_id` column on `circle` would have made the same guarantee by
overwriting the history it is the point of keeping.

**The grant is `upto_api`'s, WRITE, and that is all this revision touches.** The nightly sweep's
role is a separate question with a real cost, put to the owner rather than decided here (A24's open
list) — nothing below grants a deletion right to anybody but the API.
"""

from alembic import op
import sqlalchemy as sa

revision = "0044"
down_revision = "0043"
branch_labels = None
depends_on = None

TABLE = "join_ticket"


def _api_role() -> str:
    """Read the role's NAME from `roles.py` — the name is stable, the maps in that file are not.

    Same shape as 0034 and 0043. H59's rule is why only the name is read: a migration that imported
    a *list* from application code would apply today's list to a step in the past.
    """
    import importlib.util
    import os

    path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        "src", "upto", "roles.py",
    )
    spec = importlib.util.spec_from_file_location("_upto_roles", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.API


def upgrade() -> None:
    op.create_table(
        TABLE,
        # `bigserial`, matching every other table here — which is why the sequence needs its own
        # grant below. Revision 0032 discovers and grants the sequences that existed when it ran;
        # a table added afterwards carries its own, or `INSERT` fails with *permission denied for
        # sequence* while the table grant reads correct (0032's own paragraph).
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("circle_id", sa.BigInteger, nullable=False),
        # char(64) like `device_secret.secret_sha256`, for the same reason: a sha256 hex digest is
        # exactly 64 characters and a fixed width says so to the next reader.
        sa.Column("token_sha256", sa.CHAR(64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["circle_id"], ["circle.id"], name="fk_join_ticket_circle"),
        sa.UniqueConstraint("token_sha256", name="uq_join_ticket_hash"),
    )
    # **At most one LIVE ticket per circle.** Partial, so revoked rows pile up as the record of what
    # replaced what — which is the reason this is a table and not a column on `circle`.
    op.create_index(
        "uq_join_ticket_one_live_per_circle", TABLE, ["circle_id"],
        unique=True, postgresql_where=sa.text("revoked_at is null"),
    )
    op.execute(sa.text(
        'grant select, insert, update, delete on "{}" to "{}"'.format(TABLE, _api_role())
    ))
    op.execute(sa.text(
        'grant usage, select on sequence "{}_id_seq" to "{}"'.format(TABLE, _api_role())
    ))


def downgrade() -> None:
    op.drop_index("uq_join_ticket_one_live_per_circle", table_name=TABLE)
    op.drop_table(TABLE)
