"""A24 item 4 — the nightly sweep of abandoned self-serve circles: one column and two functions.

Revision ID: 0045
Revises: 0044
Created: 2026-09-14

Hand-written, not autogenerated (H10).

**The rulings this revision carries (owner, 2026-09-14; decision-log rows «The sweep's deletion
right», «The sweep's mechanism re-ruled», «Which circles the sweep may touch»).**

- **Which circles:** only those made through the self-serve door. `circle.self_serve` is set by
  `POST /circles` and is false for every row that exists today and for anything an operator makes.
  A circle made by the CLI is never swept; it is cleaned by hand. *Rejected:* a keep-list of ids,
  which somebody must remember to extend; sweeping everything, which would have deleted the owner's
  own rehearsal circle and the evaluator's fixtures on dates nobody chose.
- **Which of those:** a circle that never had a signed trip and that nothing has touched for thirty
  days — including one that rolled and never signed, because signing is optional and most circles
  people actually use never sign.
- **The mechanism:** one `SECURITY DEFINER` function that deletes bottom-up in an order
  written in its body, and the sweep's role (`upto_erasure`) holds EXECUTE on it and **no table
  grant at all**. *Rejected:* `ON DELETE CASCADE` from `circle` with DELETE on `circle` alone, which
  was ruled first and re-ruled when it was measured: inside a cascade PostgreSQL checks each
  foreign key as each cascaded sub-delete ends, so a circle reachable by two paths aborts depending
  on trigger-name order, and a `pg_dump` restore changes that order (H98). Written statements have
  no such order; the order is this file.

**D24's pins stay `RESTRICT`, and here they are the cross-circle backstop.** Deleting a whole circle
deletes the contributions that pin its own members' preferences first, so inside one circle the pin
is bypassed by design — the round and the preference it pinned leave together. A pin that reaches
from *another* circle's contribution is still refused by the database, which aborts the one call
and deletes nothing.

**Why two functions and not one.** The job has to list what it may sweep, and `upto_erasure` has no
SELECT on `circle`. So `circle_sweep_candidates()` holds the selection rule, and `sweep_circle(id)`
re-checks the same rule under a row lock before deleting anything — the rule lives once, and a
caller holding the credential can delete only what the rule would delete anyway.

**The functions are owned by `upto_sweeper`, a NOLOGIN role that holds nothing but what they do**
(owner, 2026-09-14, on the reviewer's pre-read). A definer function runs as its owner, and the
table owner `upto` is a superuser, so an owner-owned body would make any future slip in it
superuser-grade. `upto_sweeper` cannot log in, has no password and appears in no `.env`; it holds
SELECT and DELETE on the twelve tables the sweep empties and SELECT on `trip`, which the selection
rule reads and never deletes. Beside it: every name in the bodies is schema-qualified, the
`search_path` is pinned to `pg_catalog, pg_temp`, no service role and not `PUBLIC` holds CREATE on
schema `public` (measured 2026-09-14), and the bodies are static SQL. EXECUTE is revoked from
`PUBLIC` — PostgreSQL grants it to everyone by default — and granted to `upto_erasure` alone.

**The role is not in `roles.SERVICE_ROLES` or `roles.grants()`, and must not be.** Revision 0032
imports both at run time, so a fresh database would reach 0032's grants before this revision
creates the role. The list below is written literally for the same reason H59 gives: a migration
applies the list of its own day. `roles.SWEEPER_GRANTS` states the same list for
`test_role_grants`, which asserts the two agree with the database.

**The downgrade leaves the role in place**, revoked of every grant this revision issued. A role is
cluster-wide and another database may still hold it; `roles.ensure()` never drops a role either.
"""

from alembic import op
import sqlalchemy as sa

revision = "0045"
down_revision = "0044"
branch_labels = None
depends_on = None

#: Thirty days, as A24's Done line says. In the SQL rather than a parameter: a caller of a definer
#: function must not be able to choose the window.
IDLE_WINDOW = "30 days"

#: Below the server's `deadlock_timeout` (1 s) on purpose — see the lock paragraph in the body.
LOCK_TIMEOUT = "500ms"

# The SQLSTATEs the body raises for «not tonight» (55000 not a candidate any more, P0002 gone; the
# server raises 55P03 for the lock timeout) are READ by `upto.sweep.SKIPPED_SQLSTATES`, their one
# home; `test_circle_sweep_integration` asserts the body raises exactly those.

SWEEPER = "upto_sweeper"

#: What the functions' owner may do, and nothing else. DELETE where the sweep deletes; SELECT on
#: `trip` alone because the selection rule reads it. Written literally (H59) and mirrored by
#: `roles.SWEEPER_GRANTS`, which the grant test compares with the database.
SWEEPER_DELETES = (
    "weight_contribution", "round_forecast_baseline", "member_roll", "proposal", "preference",
    "round", "device_secret", "member", "principal", "join_ticket", "place", "circle",
)
SWEEPER_READS_ONLY = ("trip",)
#: **UPDATE on the `id` column alone, and only because a row lock needs it** — measured on 17.11:
#: `select … for update` is refused with SELECT+DELETE, and succeeds with a column-level
#: `update (id)`, which in turn refuses an UPDATE of any other column. `id` because rewriting it is
#: the least that grant can do: circle, round and member ids are referenced by NO ACTION keys, so
#: the database refuses rewriting a referenced one, and nothing references proposal.id. The body
#: never issues an UPDATE; these are the four tables it locks.
SWEEPER_LOCKS = ("circle", "round", "member", "proposal")

CANDIDATES = "public.circle_sweep_candidates()"
SWEEP = "public.sweep_circle(bigint, boolean)"


def _erasure_role() -> str:
    """Read the role's NAME from `roles.py` — same shape as 0034, 0043 and 0044 (H59)."""
    import importlib.util
    import os

    path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        "src", "upto", "roles.py",
    )
    spec = importlib.util.spec_from_file_location("_upto_roles", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.ERASURE


# **«Touched» is the latest of these writes in the circle**: the circle itself, a seat joining, a
# round opening or closing, a proposal, a tap on the dice, a preference, a place the circle named
# itself (D28's circle-local), a link minted or replaced. **Not a device secret**: one is minted with
# a seat, which `joined_at` already counts, and a secret belongs to a principal who may sit in other
# circles. `greatest` ignores nulls, so a circle with no rounds is judged on what it does have.
CANDIDATES_SQL = """
create function public.circle_sweep_candidates()
returns table (circle_id bigint, last_touch timestamptz)
language sql
stable
security definer
set search_path = pg_catalog, pg_temp
as $body$
    select touched.id, touched.last_touch
      from (
        select c.id,
               c.self_serve,
               greatest(
                   c.created_at,
                   (select max(m.joined_at) from public.member m where m.circle_id = c.id),
                   (select max(greatest(r.opened_at, r.closed_at))
                      from public.round r where r.circle_id = c.id),
                   (select max(p.proposed_at) from public.proposal p
                      join public.round r on r.id = p.round_id where r.circle_id = c.id),
                   (select max(mr.rolled_at) from public.member_roll mr where mr.circle_id = c.id),
                   (select max(pr.recorded_at) from public.preference pr
                      join public.member m on m.id = pr.member_id where m.circle_id = c.id),
                   (select max(pl.created_at) from public.place pl where pl.circle_id = c.id),
                   (select max(greatest(j.created_at, j.revoked_at))
                      from public.join_ticket j where j.circle_id = c.id)
               ) as last_touch
          from public.circle c
      ) as touched
     where touched.self_serve
       and not exists (select 1 from public.trip t where t.circle_id = touched.id)
       and touched.last_touch < now() - interval '{window}'
     order by touched.id
$body$
""".format(window=IDLE_WINDOW)


# **The order is the foreign-key graph, children first, and it is written out on purpose** (H98).
# Every step counts in a dry run and deletes otherwise, over the same predicate, so the two modes
# cannot report different sets.
#
# * `weight_contribution` first: it pins `preference` and `trip` with RESTRICT (D24, D114).
# * `trip` is never deleted: the candidate rule excludes any circle that has one, and
#   `trip → round` staying NO ACTION means a mistaken selection fails at `round` instead of
#   deleting a signed trip.
# * A **principal** goes only if this circle held its last seat. A principal can sit in several
#   circles (D74, `upto.issue --principal`), and its `device_secret` is per principal, so deleting
#   the secret of a principal who sits elsewhere would lock that person out of a circle the sweep
#   never selected.
SWEEP_SQL = """
create function public.sweep_circle(p_circle bigint, p_dry_run boolean default false)
returns table (step text, rows_affected bigint)
language plpgsql
volatile
security definer
set search_path = pg_catalog, pg_temp
set lock_timeout = '{lock_timeout}'
as $body$
declare
    n bigint;
    last_seat bigint[];
begin
    -- **Lock every row a new write would point at, THEN re-check, then delete.** Locking only the
    -- circle is not enough (the reviewer's pre-read, 2026-09-14): a proposal, a roll or a
    -- preference points at `round` or `member`, not at `circle`, so it would not wait on that
    -- lock — and under READ COMMITTED each DELETE below takes a fresh snapshot, so a proposal
    -- committed between the re-check and the proposal delete would be swept with the circle,
    -- seconds after a member acted. `for update` conflicts with the `for key share` every
    -- referencing insert takes, so from here on each such insert waits for this transaction and
    -- then fails its foreign key; one that committed before the locks were granted is seen by the
    -- re-check and makes the circle touched.
    --
    -- **The lock order is circle → round → member → proposal, and it is the product's order.**
    -- Joining a circle locks the circle first (`grow_seat`); a roll updates the round and then
    -- inserts rows pointing at member and proposal (`rounds.py`, `engine/store.py`); nothing in
    -- the API locks a round or a member and then the circle. The one path that can still form a
    -- cycle is a single INSERT whose foreign-key checks take their shares in trigger order (a
    -- proposal or a trip). **So this function waits at most `lock_timeout` for any lock, below
    -- the server's `deadlock_timeout` (1 s, measured), and the inequality is not the whole reason**
    -- (the reviewer's third pre-read): PostgreSQL runs the deadlock check `deadlock_timeout` after
    -- EACH backend began waiting, and in a cycle the member began first. The sweep still yields
    -- first because it requests its next lock within milliseconds of being granted the one the
    -- member is waiting on, so its own wait starts almost when the member's does and ends half a
    -- second later, while the member's check is due a full second after its start. The server
    -- setting is not pinned by this function; `test_circle_sweep_integration` asserts
    -- `lock_timeout < deadlock_timeout` so a lowered server setting turns a test red.
    --
    -- **The re-check is its own statement, after the locks** (the reviewer's second pre-read): a
    -- locking read that waited re-reads only the rows it locked, so a predicate folded into the
    -- same statement would miss a proposal committed while it waited. This function is VOLATILE
    -- so each statement below takes its own snapshot.
    perform 1 from public.circle where id = p_circle for update;
    if not found then
        raise exception 'sweep_circle: circle % does not exist', p_circle
            using errcode = 'no_data_found';
    end if;
    perform 1 from public.round where circle_id = p_circle for update;
    perform 1 from public.member where circle_id = p_circle for update;
    perform 1 from public.proposal
     where round_id in (select id from public.round where circle_id = p_circle) for update;
    if not exists (select 1 from public.circle_sweep_candidates() s where s.circle_id = p_circle) then
        raise exception 'sweep_circle: circle % is not sweepable (self-serve, never a signed trip, '
                        'untouched for {window})', p_circle
            using errcode = 'object_not_in_prerequisite_state';
    end if;

    select coalesce(array_agg(m.principal_id), '{{}}') into last_seat
      from public.member m
     where m.circle_id = p_circle
       and not exists (select 1 from public.member o
                        where o.principal_id = m.principal_id and o.circle_id <> p_circle);

    step := 'weight_contribution';
    if p_dry_run then
        select count(*) into n from public.weight_contribution
         where round_id in (select id from public.round where circle_id = p_circle);
    else
        delete from public.weight_contribution
         where round_id in (select id from public.round where circle_id = p_circle);
        get diagnostics n = row_count;
    end if;
    rows_affected := n; return next;

    step := 'round_forecast_baseline';
    if p_dry_run then
        select count(*) into n from public.round_forecast_baseline
         where round_id in (select id from public.round where circle_id = p_circle);
    else
        delete from public.round_forecast_baseline
         where round_id in (select id from public.round where circle_id = p_circle);
        get diagnostics n = row_count;
    end if;
    rows_affected := n; return next;

    step := 'member_roll';
    if p_dry_run then
        select count(*) into n from public.member_roll where circle_id = p_circle;
    else
        delete from public.member_roll where circle_id = p_circle;
        get diagnostics n = row_count;
    end if;
    rows_affected := n; return next;

    step := 'proposal';
    if p_dry_run then
        select count(*) into n from public.proposal
         where round_id in (select id from public.round where circle_id = p_circle);
    else
        delete from public.proposal
         where round_id in (select id from public.round where circle_id = p_circle);
        get diagnostics n = row_count;
    end if;
    rows_affected := n; return next;

    step := 'preference';
    if p_dry_run then
        select count(*) into n from public.preference
         where member_id in (select id from public.member where circle_id = p_circle);
    else
        delete from public.preference
         where member_id in (select id from public.member where circle_id = p_circle);
        get diagnostics n = row_count;
    end if;
    rows_affected := n; return next;

    step := 'round';
    if p_dry_run then
        select count(*) into n from public.round where circle_id = p_circle;
    else
        delete from public.round where circle_id = p_circle;
        get diagnostics n = row_count;
    end if;
    rows_affected := n; return next;

    step := 'device_secret';
    if p_dry_run then
        select count(*) into n from public.device_secret where principal_id = any (last_seat);
    else
        delete from public.device_secret where principal_id = any (last_seat);
        get diagnostics n = row_count;
    end if;
    rows_affected := n; return next;

    step := 'member';
    if p_dry_run then
        select count(*) into n from public.member where circle_id = p_circle;
    else
        delete from public.member where circle_id = p_circle;
        get diagnostics n = row_count;
    end if;
    rows_affected := n; return next;

    step := 'principal';
    if p_dry_run then
        select count(*) into n from public.principal where id = any (last_seat);
    else
        delete from public.principal where id = any (last_seat);
        get diagnostics n = row_count;
    end if;
    rows_affected := n; return next;

    step := 'join_ticket';
    if p_dry_run then
        select count(*) into n from public.join_ticket where circle_id = p_circle;
    else
        delete from public.join_ticket where circle_id = p_circle;
        get diagnostics n = row_count;
    end if;
    rows_affected := n; return next;

    step := 'place';
    if p_dry_run then
        select count(*) into n from public.place where circle_id = p_circle;
    else
        delete from public.place where circle_id = p_circle;
        get diagnostics n = row_count;
    end if;
    rows_affected := n; return next;

    step := 'circle';
    if p_dry_run then
        n := 1;
    else
        delete from public.circle where id = p_circle;
        get diagnostics n = row_count;
    end if;
    rows_affected := n; return next;
end
$body$
""".format(window=IDLE_WINDOW, lock_timeout=LOCK_TIMEOUT)


def upgrade() -> None:
    # Existing rows are false by the default, which is the ruling: nothing made before this
    # revision came through the self-serve door as far as the database can tell, and a circle the
    # sweep cannot prove is self-serve is never swept.
    op.add_column(
        "circle",
        sa.Column("self_serve", sa.Boolean, nullable=False, server_default=sa.false()),
    )
    # Idempotent, and `nologin` re-asserted on every run: the role is cluster-wide, so it may
    # already exist from another database, and a role this revision relies on being unable to log
    # in must be unable to log in whatever state it was found in.
    op.execute(sa.text(
        "do $role$ begin "
        "if not exists (select 1 from pg_roles where rolname = '{0}') then "
        'create role "{0}" nologin; '
        "end if; end $role$".format(SWEEPER)))
    op.execute(sa.text('alter role "{}" nologin'.format(SWEEPER)))
    for table in SWEEPER_DELETES:
        op.execute(sa.text('grant select, delete on public."{}" to "{}"'.format(table, SWEEPER)))
    for table in SWEEPER_READS_ONLY:
        op.execute(sa.text('grant select on public."{}" to "{}"'.format(table, SWEEPER)))
    for table in SWEEPER_LOCKS:
        op.execute(sa.text('grant update (id) on public."{}" to "{}"'.format(table, SWEEPER)))

    op.execute(sa.text(CANDIDATES_SQL))
    op.execute(sa.text(SWEEP_SQL))
    erasure = _erasure_role()
    for signature in (CANDIDATES, SWEEP):
        op.execute(sa.text('alter function {} owner to "{}"'.format(signature, SWEEPER)))
        op.execute(sa.text("revoke all on function {} from public".format(signature)))
        op.execute(sa.text('grant execute on function {} to "{}"'.format(signature, erasure)))


def downgrade() -> None:
    op.execute(sa.text("drop function {}".format(SWEEP)))
    op.execute(sa.text("drop function {}".format(CANDIDATES)))
    for table in SWEEPER_DELETES + SWEEPER_READS_ONLY:
        op.execute(sa.text('revoke all on public."{}" from "{}"'.format(table, SWEEPER)))
    op.drop_column("circle", "self_serve")
